---
title: "Projects"
title-block-banner: ../images/headers/projects_header.png
format: html
listing:
  type: grid
  contents: projects_profiles
  sort: name
  fields: [image, name, research]
  grid-columns: 1
  image-height: 175px
  page-size: 0
---

::: {.callout .testimonial}

> "This internship absolutely positively impacted my university experience because it not only gave me hours of field experience required for other classes and added experience to my resume, but also gave me excitement for my major that sitting in a class lecture simply can’t achieve."
>
> — K.S. (undergraduate intern, Fall 2023)

:::
 
::: {.callout .testimonial}

> "Gaining experience in the field I want to pursue while in University 100% makes my experience so much better. Working on projects like this make me want my degree all that much more!"
>
> — H.W. (undergraduate intern, Fall 2024)

:::
 



With WYOBIRDhope to attract diverse students interested in birds and wildlife to UW while providing existing students with resources. Our local projects allow UW students to gain hands-on experience with bird research in an accessible way close to home. Students involved in WYOBIRD are exposed to field techniques such as bird capture and handling, nest monitoring, data management, project logistics, habitat sampling, behavioral observations, science communication, and more while contributing to research on birds within and beyond Wyoming. Each field season we support avian interns who assist with our local projects. Students learn valuable skills and gain UW university credit for their time. We hope to train and mentor several interns each fall and actively fundraise so that we can provide paid internships in the future. See the [Support Us!](../support/support_us.qmd) page to help us meet this goal!