---
title: "People"
title-block-banner: ../images/headers/people_header.png
format: html
listing:
  type: grid
  contents: ind_profiles
  sort: name
  fields: [image, name, research]
  grid-columns: 4
  image-height: 160px
  page-size: 0
---

Most WYOBIRD faculty, staff, and students are housed in the Department of Zoology and Physiology under the College of Agriculture, Life Sciences and Natural Resources. However, WYOBIRD is open to all students interested in studying birds and we collaborate with people, labs, and schools within and beyond the University of Wyoming. We offer internships for undergraduates where they gain UW credit hours while assisting with field projects in the Laramie area. See the [Get Involved](../get_involved/get_involved.qmd) page for more information on how to participate in WYOBIRD.

Faculty and their students conduct research on a diversity of avian species and habitats within the state of Wyoming as well as in locations far beyond such as Panama and Hawaii. Projects examine questions on community structure, seed dispersal networks, hybrid zones, migratory movements, long-term demographic trends, impacts of energy development, animal communication, window collisions, avian parasites and more. Check out the faculty lab websites for more information on their work and how to join their labs.

- **Corey Tarwater (Director, WYOBIRD)** – ecology and demography of tropical bird species
- **Anna Chalfoun (Associate Director, WYOBIRD)** – wildlife-habitat relationships, especially of songbirds in sagebrush systems
- **Matt Carling (Associate Director, WYOBIRD)** - patterns and mechanisms underlying speciation in adaptation in birds
- **Jessie Williamson (Associate Director, WYOBIRD)** – evolutionary physiology in mountain birds
- **Patrick Kelley (Associate Director, WYOBIRD)** - behavioral ecology of tropical birds

## WYOBIRD Team
